name: Deploy WordPress to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIATFBMPPUBED3J3E7X
          aws-secret-access-key: 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
          aws-region: eu-north-1  
          
      - name: Debug S3 buckets
        run: aws s3 ls
          
      - name: Zip WordPress app
          run: |
          zip -r app.zip . -x ".git/*" ".github/*"

      - name: Upload zip to S3
        run: |
          aws s3 cp app.zip s3://elasticbeanstalk-eu-north-1-216989138178/app-${{ github.sha }}.zip

      - name: Create EB app version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-216989138178,S3Key=app-${{ github.sha }}.zip

      - name: Update EB environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label ${{ github.sha }}
